# Copy-paste each block one at a time

# 0a. Upload TRANSIN.DAT
curl -T "/home/ubuntu/Cobol Code Final/cobol/TRANSIN.DAT" ftp://localhost:2121/ --user herc01:cul8tr

# 0b. Upload ACCTMAST.DAT
curl -T "/home/ubuntu/Cobol Code Final/cobol/ACCTMAST.DAT" ftp://localhost:2121/ --user herc01:cul8tr

# 1. Create HERC01.LOAD
echo "//ALLOC    JOB (ACCT),'ALLOC',CLASS=A,USER=HERC01,PASSWORD=CUL8TR
//STEP     EXEC PGM=IEFBR14
//LOAD     DD DSN=HERC01.LOAD,DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(1,1,10)),
//             DCB=(RECFM=U,LRECL=0,BLKSIZE=32760)
//SYSOUT   DD SYSOUT=*
//" > /tmp/01_alloc.jcl
curl -T /tmp/01_alloc.jcl ftp://localhost:2121/ --user herc01:cul8tr
sleep 4

# 2. Compile VALDTRAN
echo "//VALDCOMP JOB (ACCT),'COMP-VALD',CLASS=A,USER=HERC01,PASSWORD=CUL8TR
//COB      EXEC PGM=IKFCBL00,PARM='LOAD,NODECK,SIZE=2048K,BUF=1024K'
//SYSPRINT DD SYSOUT=*
//SYSUT1   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSUT2   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSUT3   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSUT4   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSLIN   DD DSN=&&LOADSET,DISP=(MOD,PASS),
//             UNIT=SYSDA,SPACE=(80,(500,100))
//SYSIN    DD DATA
$(cat "/home/ubuntu/Cobol Code Final/cobol/VALDTRAN.cbl")
/*
//SYSPUNCH DD DUMMY
//LKED     EXEC PGM=IEWL,PARM='LIST,XREF'
//SYSLIB   DD DSN=SYS1.COBLIB,DISP=SHR
//SYSLIN   DD DSN=&&LOADSET,DISP=(OLD,DELETE)
//SYSLMOD  DD DSN=HERC01.LOAD(VALDTRAN),DISP=SHR
//SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSPRINT DD SYSOUT=*
//" > /tmp/02_valdcomp.jcl
curl -T /tmp/02_valdcomp.jcl ftp://localhost:2121/ --user herc01:cul8tr
sleep 5

# 3. Compile UPDTBAL
echo "//UPDTCOMP JOB (ACCT),'COMP-UPDT',CLASS=A,USER=HERC01,PASSWORD=CUL8TR
//COB      EXEC PGM=IKFCBL00,PARM='LOAD,NODECK,SIZE=2048K,BUF=1024K'
//SYSPRINT DD SYSOUT=*
//SYSUT1   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSUT2   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSUT3   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSUT4   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSLIN   DD DSN=&&LOADSET,DISP=(MOD,PASS),
//             UNIT=SYSDA,SPACE=(80,(500,100))
//SYSIN    DD DATA
$(cat "/home/ubuntu/Cobol Code Final/cobol/UPDTBAL.cbl")
/*
//SYSPUNCH DD DUMMY
//LKED     EXEC PGM=IEWL,PARM='LIST,XREF'
//SYSLIB   DD DSN=SYS1.COBLIB,DISP=SHR
//SYSLIN   DD DSN=&&LOADSET,DISP=(OLD,DELETE)
//SYSLMOD  DD DSN=HERC01.LOAD(UPDTBAL),DISP=SHR
//SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSPRINT DD SYSOUT=*
//" > /tmp/03_updtcomp.jcl
curl -T /tmp/03_updtcomp.jcl ftp://localhost:2121/ --user herc01:cul8tr
sleep 5

# 4. Compile RPRTGEN
echo "//RPRTCOMP JOB (ACCT),'COMP-RPRT',CLASS=A,USER=HERC01,PASSWORD=CUL8TR
//COB      EXEC PGM=IKFCBL00,PARM='LOAD,NODECK,SIZE=2048K,BUF=1024K'
//SYSPRINT DD SYSOUT=*
//SYSUT1   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSUT2   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSUT3   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSUT4   DD UNIT=SYSDA,SPACE=(460,(700,100))
//SYSLIN   DD DSN=&&LOADSET,DISP=(MOD,PASS),
//             UNIT=SYSDA,SPACE=(80,(500,100))
//SYSIN    DD DATA
$(cat "/home/ubuntu/Cobol Code Final/cobol/RPRTGEN.cbl")
/*
//SYSPUNCH DD DUMMY
//LKED     EXEC PGM=IEWL,PARM='LIST,XREF'
//SYSLIB   DD DSN=SYS1.COBLIB,DISP=SHR
//SYSLIN   DD DSN=&&LOADSET,DISP=(OLD,DELETE)
//SYSLMOD  DD DSN=HERC01.LOAD(RPRTGEN),DISP=SHR
//SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSPRINT DD SYSOUT=*
//" > /tmp/04_rprtcomp.jcl
curl -T /tmp/04_rprtcomp.jcl ftp://localhost:2121/ --user herc01:cul8tr
sleep 10

# 5. Run BANKRUN
echo "//BANKRUN  JOB (ACCT),'BANK-RUN',CLASS=A,USER=HERC01,PASSWORD=CUL8TR
//ALLOC    EXEC PGM=IEFBR14
//VALIDATE DD DSN=HERC01.VALIDATE,DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(1,1)),
//             DCB=(RECFM=FB,LRECL=80,BLKSIZE=800)
//ACCTUPD  DD DSN=HERC01.ACCTUPD,DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(1,1)),
//             DCB=(RECFM=FB,LRECL=80,BLKSIZE=800)
//SYSOUT   DD SYSOUT=*
//VALD     EXEC PGM=VALDTRAN
//STEPLIB  DD DSN=HERC01.LOAD,DISP=SHR
//TRANSIN DD DATA
$(cat "/home/ubuntu/Cobol Code Final/cobol/TRANSIN.DAT")
/*
//VALIDATE DD DSN=HERC01.VALIDATE,DISP=OLD
//VALERR   DD SYSOUT=*
//ACCTMAST DD DATA
$(cat "/home/ubuntu/Cobol Code Final/cobol/ACCTMAST.DAT")
/*
//SYSOUT   DD SYSOUT=*
//UPDT     EXEC PGM=UPDTBAL
//STEPLIB  DD DSN=HERC01.LOAD,DISP=SHR
//VALIDATE DD DSN=HERC01.VALIDATE,DISP=OLD
//ACCTMAST DD DATA
$(cat "/home/ubuntu/Cobol Code Final/cobol/ACCTMAST.DAT")
/*
//ACCTUPD  DD DSN=HERC01.ACCTUPD,DISP=OLD
//UPDRPT   DD SYSOUT=*
//SYSOUT   DD SYSOUT=*
//RPT      EXEC PGM=RPRTGEN
//STEPLIB  DD DSN=HERC01.LOAD,DISP=SHR
//ACCTUPD  DD DSN=HERC01.ACCTUPD,DISP=OLD
//FINALRPT DD SYSOUT=*
//SYSOUT   DD SYSOUT=*
//" > /tmp/05_bankrun.jcl
curl -T /tmp/05_bankrun.jcl ftp://localhost:2121/ --user herc01:cul8tr
